### ISSUE TITLE
Plugin processes also binary files

### ISSUE THREAD

**Issue by juhamust** [evoja/metalsmith-prefixoid#1]
It seems that (at least some) binary files get processed by the plugin, which is naturally not wanted: When enabled, the PNG images outcome invalid.

I'd suggest adding some kind of pattern support which files are to be processed or not: https://www.npmjs.com/package/multimatch

**Comment by chivorotkiv** [comment]
That's a good idea @juhamust.

As for me I met the same problem with some other plugins and used [metalsmith-hideshow](https://github.com/evoja/metalsmith-hideshow/) to solve that. I want to add pattern support there some day, but it's already useable.

**Comment by chivorotkiv** [comment]
now it is available in metalsmith-prefixoid@0.0.6-s1

**Comment by juhamust** [comment]
Excellent! Thanks for the quick response time.
