### ISSUE TITLE
< > characters get espaced in CSS files

### ISSUE THREAD

**Issue by juhamust** [evoja/metalsmith-prefixoid#3]
Plugin is causing some issues with CSS files. Here's the CSS file w/ and w/o plugin:

```diff
diff site.css site.prefixoid.css 
100c100
< .page > * {
---
> .page &gt; * {
132c132
< .page .main-pane .wrapper > * {
---
> .page .main-pane .wrapper &gt; * {
224c224
< .page.front .main-pane .highlights > * {
---
> .page.front .main-pane .highlights &gt; * {
```

I'm using default pattern (related to #1 ), so it should not touch css -files, right? But apparently there is still there something in the process that causes the issue.

**Comment by chivorotkiv** [comment]
@juhamust 
Fixed. `metalsmith-prefixoid@0.0.6-s2`
